runtime:
  cache_dir: ./.cache/antora

site:
  title: Red Hat Quay Workshop
  url: https://olleb.com/quay-workshop
  start_page: quay-workshop::index.adoc

content:
  branches: [v*, main]
  sources:
    - url: .
      start_path: documentation

asciidoc:
  attributes:
    release-version: main
    page-pagination: true
    openshift-version: '4.19.8'
    quay-version: '3.15'
  extensions:
    - ./lib/tab-block.js
    - ./lib/remote-include-processor.js

ui:
  bundle:
    url: https://github.com/aolle/rhd-tutorial-ui/releases/download/v0.2.0/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: partials/toolbar.hbs
      contents: ./supplemental-ui/partials/toolbar.hbs
    - path: .nojekyll
    - path: ui.yml
      contents: "static_files: [ .nojekyll ]"
    - path: js/version-name.js
      contents: ./supplemental-ui/js/version-name.js

output:
  dir: ./gh-pages
